"""Add GameQuestion and GameResult models

Revision ID: 5dde306a2086
Revises: b18b21e3c738
Create Date: 2025-06-21 20:25:25.186394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dde306a2086'
down_revision = 'b18b21e3c738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('question', sa.String(length=200), nullable=True),
    sa.Column('correct_answer', sa.String(length=50), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('choosen_answer', sa.String(length=50), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['game_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_result')
    op.drop_table('game_question')
    # ### end Alembic commands ###
