"""Add password and Google ID to User model

Revision ID: b18b21e3c738
Revises: 
Create Date: 2025-06-14 16:05:26.833451
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b18b21e3c738'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint('uq_google_id', ['google_id'])  # ✅ Named constraint

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_google_id', type_='unique')  # ✅ Must use the same name
        batch_op.drop_column('google_id')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
