"""Fix typo in GameResult column

Revision ID: f54480efdce7
Revises: 5dde306a2086
Create Date: 2025-06-22 10:46:23.226429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54480efdce7'
down_revision = '5dde306a2086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chosen_answer', sa.String(length=50), nullable=True))
        batch_op.drop_column('choosen_answer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('choosen_answer', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('chosen_answer')

    # ### end Alembic commands ###
